### PR TITLE
Update spelling of WHO

### PR DESCRIPTION
**Pull request by mariabnd**
They spell organisation with a Z

### CODE REVIEW

**Comment by seabbs** [comment]
Awesome - thanks for this @mariabnd! 

I have had my eye on this for a while but have been stubbornly not changing it. 

When searching the package (https://github.com/seabbs/getTBinR/search?q=organisation&unscoped_q=organisation) I see quite a few instances where I have done this. Do you think it would make sense to go through and change everywhere (excepting the citation and paper - those will have to stay for posterity)? 

If so would you be up for doing that :smile:?

**Comment by mariabnd** [comment]
Sure, will get that done asap

**Comment by mariabnd** [comment]
Think I managed to get all the ones from the link

**Comment by seabbs** [comment]
Looks good to me - thanks for updating that. Merging now

**Comment by seabbs** [comment]
Just added to `news.md` to finish everything off. Nice job managing the test updates by the way - happy to take suggestions to make things better.

**Pull request merged**
